title: 3M Studio Docs
description: Documentation for 3M Studio skripts
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: /assets/images/3m-banner.png
search_enabled: true
aux_links_new_tab: true
footer_content: "© 3M Studio"
plugins:
  - jekyll-seo-tag

just_the_docs:
  enable_copy_code_button: true   # copy gumb iznad code-blokova
  # (po želji) podebljaj širinu sadržajaa:
  # content_width: "980px"

stylesheets:
  - /assets/css/custom.css
